const express = require("express");
const ExpressError = require("./ExpressError");
const app = express();

app.get("/err", (req, res) => {
  abcd = abcd;
});

app.use((err, req, res, next) => {
  //   console.log(err);
  console.log("---- ERROR ----");
  //   return next(); //it will pass the control to next non error handling middleware
  return next(err); //it will pass the control to next error handling middleware
});
app.use((err, req, res, next) => {
  //   console.log(err);
  console.log("---- ERROR2 Middleware ----");
  return next(err);
});

const checkToken = (req, res, next) => {
  let { token } = req.query;
  if (token === "giveAccess") {
    return next();
  } else {
    throw new ExpressError(401, "ACCESS DENIED!");
  }
};

app.get("/api", checkToken, (req, res, next) => {
  res.send("Data");
});

// app.use((err, req, res, next) => {
//   console.log("---- ERROR ----");
//   res.send(err); //send error to client side which is generated by ExpressError class
//   //   return next(err); //send control to express default error handler
// });

app.use("/admin", (req, res) => {
  throw new ExpressError(403, "Access to admin is forbidden");
});

app.use((err, req, res, next) => {
  let { status = 500, message = "some error occured" } = err;
  res.status(status).send(message);
  //   res.send(err); //sends error object on the client side
});

app.use((req, res) => {
  res.status(404).send("Invalid URL");
});

app.listen(8080, () => {
  console.log("listening on port 8080");
});
